### ISSUE TITLE
create the ui for the community 

### ISSUE THREAD

**Issue by Maheeshi** [Maheeshi/PUSL-2021#4]
It's a platform where people can either share posts or video calls and communicate with each other. 
![Screenshot 2024-02-10 070253](https://github.com/Maheeshi/PUSL-2021/assets/132429336/9470127a-f4ef-430c-b050-0a2a27968945)
this is just to give you an idea if we are using something like facebook sharing posts but they can only share appropriate content.

**Comment by RAWINISATHEESHA** [comment]
IS THE MEETING POSTPONED OR SOMETHING? IF THERE ARE ANY PLEASE LET ME
KNOW....
I'D LIKE YOU NOT TO TEXT BACK ON WHATSAPP BECAUSE WHATSAPP WEB WAS ALSO
DELETED.

**Comment by RAWINISATHEESHA** [comment]
[SIGNGRAM.zip](https://github.com/Maheeshi/PUSL-2021/files/14544823/SIGNGRAM.zip)
HERE THE COMMUNITY `UI`

**Comment by RAWINISATHEESHA** [comment]
[SIGNGRAM.zip](https://github.com/Maheeshi/PUSL-2021/files/14627908/SIGNGRAM.zip)
